### ISSUE TITLE
Supabase Functions to supports GET (and other) requests

### ISSUE THREAD

**Issue by mlanza** [supabase/functions-relay#11]
# Feature request

## Is your feature request related to a problem? Please describe.

I may not be seeing everything so I apologize for whatever I may be overlooking.

There are problems that present themselves when you have only POST requests to work with.  If you consider that command-query separation is a well-appreciated approach for writing software, you are reminded that nearly all software relies on commands and queries.  The commands effect change in the system and the queries provide views of data to inform decisions and, in turn, are used to issue commands.  Serverless functions should, thus, afford both.

POST has only the connotation of issuing a command.  So what you have when POST is all you can do is a system which issues commands but cannot be queried.  It's true you can query the database directly via a client library, but this loses one of the native benefits of HTTP: [caching](https://tech.ebayinc.com/engineering/caching-http-post-requests-and-responses/).

When I put my database calls behind an HTTP GET endpoint I gain this for free.  It reduces network chatter and improves app response time, all without any special coding.  Whenever the app asks for something it previously requested (e.g. same endpoint, same query string), I get it for free because my GETs are idempotent, and cached in my browser!

I'm offering an argument for having the complete set of HTTP methods on the roadmap.  Otherwise, once a developer needs a query function he'll be forced, as I was, to look elsewhere.  It wouldn't make sense for a developer to use Supabase's Edge Functions along side Cloudflare Workers.  Rather, for consistency's sake, he'll opt into the more robust offering.

Obviously, my use case is specific.  I benefit from cacheable GET requests.  It would seem, however, that providing serverless functions that, in certain situations, require developers to look elsewhere make them too fragile to build upon.  That is, why would one build on POST-only functions knowing the minute he needs a cacheable GET request he'll require another vendor?

## Describe the solution you'd like

Functions which comprehensively support other methods, esp. GET, fill the gaps needed by many apps.  With GET implemented, at the very least, many network responses can be cached and thus ignored altogether.  It also permits JAMStack-friendly service providers like Cloudflare to cache on the edge and not just in the browser.

## Describe alternatives you've considered

I considered using the Supabase client to hit the database directly in lieu of HTTP GETs.  It gets me the data but not the cache.  I could implement caching logic in the client but that's work I don't have to do with an HTTP GET.

I'm considering using Cloudflare Workers which handle HTTP GET/POST.

**Comment by laktek** [comment]
@mlanza Thanks for sharing this feedback. Yes, support for other HTTP verbs other than POST is something we're working on (incl. GET). Will update this issue when we release it.

**Comment by mlanza** [comment]
Super.  I figured it was probable but not seeing mention in the docs/blog esp. pertaining to Edge Functions, I just wanted to be sure it was on the roadmap.

Thank you.

**Comment by laktek** [comment]
Closing this issue. We'll update when we release this feature.

**Comment by mlanza** [comment]
I have implemented my app's functionality with Workers so this issue is not critical to my work.  I still think it's a critical offering for Edge Functions for reasons already mentioned.
