### ISSUE TITLE
502 Bad Gateway Error when Deploying Edge Function

### ISSUE THREAD

**Issue by RoastedPecans** [supabase/functions-relay#2]
# Bug report

## Describe the bug

When deploying any of my Supabase Edge Functions, I now receive a 502 error on invoke along with no logs being generated in the Supabase web GUI.

This bug was first noticed when re-deploying a function to change two string literals. However, I was able to reproduce it with edge functions that were not changed at all.

## To Reproduce

1. Deploy Edge Function to Supabase.
2. Invoke Edge Function either via Node Library or cURL
3. Get error `502: Bad Gateway (DEPLOYMENT_FAILED)`

## Expected behavior

I expect to receive my function output. Instead, I receive a 502 error.

## System information

- OS: macOS
- Version of supabase-js: 0.26.1
- Version of Node.js: 8.2.0

## Additional context

I was successfully using Supabase Edge Functions to integrate with the Stripe API until two days ago. Then, randomly on a re-deploy of my function, I began encountering this error. I have tried reinitializing the Supabase CLI, relinking to my project, re-deploying, deleting the functions, and reverting the Edge Functions back to previous known working versions. All result in 502 error.

I've seen similar Issues in this repo where it was reported to be a script size / memory limit, but I do not see why this would be relevant if I am redeploying the same code.

Can provide any additional information / context required.

**Comment by RoastedPecans** [comment]
Thanks for transferring that, wasn’t quite sure where to leave it.

Project Slug is mhjgqqffbeagyjshgcnr

**Comment by RoastedPecans** [comment]
@kiwicopple Any updates on this? I am still getting 502 errors when deploying my functions via the supabase CLI

**Comment by andymitch** [comment]
Hi, I'm on @RoastedPecans' team trying to get this resolved as well. Having used Deno Deploy before, my guess is the error is coming directly from Deno but Supabase isn't passing along the error message resulting in an arbitrary 502 error.

**Comment by soedirgo** [comment]
Can you try wrapping the function body in try/catch and logging the errors? We also have an issue with `console.error` logs not showing on the dashboard right now, but you can use `console.log` etc.

**Comment by inian** [comment]
Looks like there is an error with Stripe and Deno at the moment. Lets continue the discussion [here](https://github.com/supabase/supabase/issues/7878)
