### ISSUE TITLE
Egde function don't log console.error

### ISSUE THREAD

**Issue by riderx** [supabase/functions-relay#3]
# Bug report

## To Reproduce

- Create a basic function with `console.error("test")`
- invoque the function
- try to find your message `test` in the logs 

## Expected behavior

The console error should be visible

**Comment by burmecia** [comment]
This issue is sourced from upstream Deno, and it has been fixed now.

**Comment by riderx** [comment]
@burmecia do you have link to deno issue maybe ?

**Comment by inian** [comment]
This was an issue with [Deno Subhosting](https://deno.com/deploy/docs/subhosting) and how it interacted with our logging pipeline, and not the deno language itself @riderx. Are you still seeing errors not logged?

**Comment by riderx** [comment]
Thanks for the insight, i didn't try to switch back the message to error, i will soon but i trust you did fix it !
